#! /bin/sh

setxkbmap -layout tr -variant f -option caps:escape

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  "I" "II" "III" "IV" "V"
#bspc monitor -d "   " "  " "  " "  " "  " 

bspc config border_width        2
#bspc config border_radius       10
bspc config window_gap          10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config normal_border_color     "#141414" #"#434C5E" # "#1E2127"     
bspc config focused_border_color    "#303030"
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh /home/berkay/.config/bspwm/autostart.sh
