#! /bin/sh

setxkbmap -layout tr -variant f -option caps:escape

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width        4
bspc config border_radius       15
bspc config window_gap          12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config normal_border_color     "#1E2127"     
bspc config focused_border_color    "#61AFEF"
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh /home/berkay/.config/bspwm/autostart.sh
